# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "James Wright"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.jameswright.xyz/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
# copyright = "&copy; {year} James Wright"

copyright = """
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
<img style="display:block;margin: 0 auto" class="display-centered" alt="Creative Commons License"
src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
</a>
<br />
<span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">
This work</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="/" property="cc:attributionName"
rel="cc:attributionURL">James Wright</a> is licensed under a <a rel="license"
href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0
International License</a>.<br />
Permissions beyond the scope of this license may be available at <a
xmlns:cc="http://creativecommons.org/ns#" href="mailto:james@jameswright.xyz"
rel="cc:morePermissions">james@jameswright.xyz</a>."""

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
	[markup.blackfriday]
		hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
		angledQuotes = false
		latexDashes = true
		extensions = ["backslashLineBreak"]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[privacy.googleAnalytics]
	anonymizeIP = true
	disable = false
	respectDoNotTrack = true
	useSessionStorage = false

[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

  [[related.indices]]
    name = "authors"
    weight = 20.0

[permalinks]
  post = '/:section/:year:month:day/:slug'

############################
## Hugo Modules Setup
############################
[module]

  # [[module.imports]] # pretty sure I don't need
  #   path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms"
  #   disable = true
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5"

[security.funcs]
  getenv = [ "^HUGO_", "^WC_" ]
