[appearance]
mode = 'system'
color = 'green'

[marketing.seo]
site_type = "Person"
local_business_type = ""
org_name = ""
description = ""
twitter = ""

[marketing.analytics]
google_analytics = "UA-162278003-2"
baidu_tongji = ""

[marketing.verification]
google = ""
baidu = ""

[header.navbar]
enable = true
align = "l"
logo.text = "James Wright"
show_logo = true
show_language = false
show_day_night = false
show_search = true
highlight_active_link = true

[footer.copyright]
notice = "© {year} James Wright. This work is licensed under {license}"

  [footer.copyright.license]
  enable = true
  allow_derivatives = true
  share_alike = true
  allow_commercial = true

[locale]
date_format = "Jan 2, 2006"
time_format = "3:04 PM"
address_format = "en-us"

[features.syntax_highlighter]
enable = true
extra_languages = [ "r", "latex" ]

[features.math]
enable = true

[features.privacy_pack]
enable = true

[features.repository]
url = "https://github.com/jrwrigh/jameswright.xyz_source"
content_dir = ""
branch = "master"

[features.avatar]
gravatar = false
shape = "square"

[features.comment]
provider = "giscus"

  [features.comment.disqus]
  shortname = ""
  show_count = true

  [features.comment.commento]
  url = ""

  [features.comment.giscus]
  repo = "jrwrigh/jameswright.xyz_source"
  repo_id = "MDEwOlJlcG9zaXRvcnkyMjQ3MDg3OTY="
  category= "Announcements"
  category-id= "DIC_kwDODWTIvM4CRoHq"
  theme= "dark_dimmed"

[features.search]
provider = "wowchemy"

  [features.search.algolia]
  app_id = ""
  api_key = ""
  index_name = ""
  show_logo = false

[features.map]
provider = ""
api_key = ""
zoom = 15

[extensions.cms]
branch = "master"
local_backend = false

[extensions.isotope]
enable = true

[extensions.academicons]
enable = true
